import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const starjedi = localFont({
  src: './assets/fonts/Starjedi.ttf',
  display: 'swap',
  variable: '--font-starjedi'
})

const starjhol = localFont({
  src: './assets/fonts/starjhol.ttf',
  display: 'swap',
  variable: '--font-starjhol'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${starjedi.variable} ${starjhol.variable}`}>
        {children}
      </body>
    </html>
  );
}
